# Why NumPy?

In [23]:
a = [1,2,3,4]
b = [2,3,4,5]

In [24]:
ab = []
for i in range(0, len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [25]:
import numpy as np

In [26]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [27]:
a*b

array([ 2,  6, 12, 20])

# Creating a NumPy Array

In [28]:
import numpy as np

In [29]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [30]:
a = np.array([1,2,3,4,5])

In [31]:
type(a)

numpy.ndarray

In [32]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [33]:
# create an array from scratch

In [34]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [37]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [38]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
np.random.normal(10, 4, (3,4))

array([[ 8.67237259, 11.38498771, 10.84636181,  8.86856525],
       [16.32570062,  9.66852332,  8.98160796, 17.61256868],
       [14.98912366, 11.1771283 ,  8.50721851,  8.83367782]])

In [40]:
np.random.randint(0,10,(3,3))

array([[2, 4, 4],
       [7, 1, 0],
       [8, 9, 9]])

# Properties

* **ndim**: size number
* **shape**: size information
* **size**: total number of elements
* **dtype**: array data type

In [41]:
import numpy as np

In [42]:
np.random.randint(10, size = 10)

array([5, 5, 4, 7, 0, 1, 3, 7, 3, 0])

In [43]:
a = np.random.randint(10, size = 10)

In [44]:
a.ndim

1

In [45]:
a.shape

(10,)

In [46]:
a.size

10

In [47]:
a.dtype

dtype('int32')

In [50]:
b = np.random.randint(10, size = (3,5))

In [51]:
b

array([[2, 8, 2, 6, 7],
       [2, 7, 1, 1, 7],
       [0, 2, 7, 3, 5]])

In [52]:
b.ndim

2

In [53]:
b.shape

(3, 5)

In [54]:
b.size

15

In [55]:
b.dtype

dtype('int32')

# Reshaping

In [56]:
import numpy as np

In [57]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a = np.arange(1,10)

In [60]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a.ndim

1

In [62]:
b = a.reshape((1,9)) 

In [63]:
b.ndim

2

# Array Concatenation

In [65]:
import numpy as np

In [66]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [67]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [68]:
z = np.array([7,8,9])

In [69]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# two sizes

In [71]:
a = np.array([[1,2,3],
             [4,5,6]])

In [73]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([a, a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Splitting

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])

In [3]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [4]:
a,b,c = np.split(x,[3,5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([99, 99])

In [7]:
c

array([3, 2, 1])

In [8]:
# two-dimensional splitting

In [9]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [11]:
up, down = np.vsplit(m, [2])

In [12]:
up

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
down

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [16]:
right, left = np.hsplit(m, [2])

In [17]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [18]:
left

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sorting

In [19]:
import numpy as np

In [20]:
v = np.array([2,1,4,3,5])

In [21]:
v

array([2, 1, 4, 3, 5])

In [22]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [23]:
v

array([2, 1, 4, 3, 5])

In [24]:
v.sort()

In [25]:
v

array([1, 2, 3, 4, 5])

In [26]:
# two-dimensional array sorting

In [28]:
m = np.random.normal(20,5,(3,3))

In [29]:
m

array([[22.6586502 , 22.08400809, 14.49737267],
       [25.63077718, 16.87550454, 14.16743861],
       [19.7035397 , 26.66869578, 24.67457957]])

In [30]:
np.sort(m, axis = 1)

array([[14.49737267, 22.08400809, 22.6586502 ],
       [14.16743861, 16.87550454, 25.63077718],
       [19.7035397 , 24.67457957, 26.66869578]])

In [31]:
np.sort(m, axis = 0)

array([[19.7035397 , 16.87550454, 14.16743861],
       [22.6586502 , 22.08400809, 14.49737267],
       [25.63077718, 26.66869578, 24.67457957]])

# Accessing Elements with Index

In [33]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([4, 0, 7, 5, 4, 0, 8, 0, 7, 5])

In [34]:
a[0]

4

In [35]:
a[-1]

5

In [36]:
a[0] = 100

In [37]:
a

array([100,   0,   7,   5,   4,   0,   8,   0,   7,   5])

In [38]:
m = np.random.randint(10, size = (3,5))
m

array([[5, 5, 1, 8, 3],
       [1, 9, 0, 2, 6],
       [5, 9, 2, 0, 5]])

In [39]:
m[0,0]

5

In [40]:
m[1,1]

9

In [42]:
m[1,4]

6

In [43]:
m[1,4] = 99

In [44]:
m

array([[ 5,  5,  1,  8,  3],
       [ 1,  9,  0,  2, 99],
       [ 5,  9,  2,  0,  5]])

In [45]:
m[1,4] = 2.2

In [46]:
m

array([[5, 5, 1, 8, 3],
       [1, 9, 0, 2, 2],
       [5, 9, 2, 0, 5]])

# Accessing Elements with Slicing

In [47]:
import numpy as np

In [48]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
a[0:3]

array([20, 21, 22])

In [50]:
a[:3]

array([20, 21, 22])

In [51]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [52]:
a[1::2]

array([21, 23, 25, 27, 29])

In [53]:
a[0::2]

array([20, 22, 24, 26, 28])

In [54]:
a[2::2]

array([22, 24, 26, 28])

In [55]:
a[0::3]

array([20, 23, 26, 29])

In [56]:
# two-dimensional slicing operations

In [57]:
m = np.random.randint(10, size = (5,5))

In [58]:
m

array([[7, 0, 7, 6, 8],
       [3, 0, 3, 3, 0],
       [4, 7, 8, 5, 3],
       [5, 1, 3, 1, 4],
       [5, 8, 8, 2, 6]])

In [59]:
m[:,0]

array([7, 3, 4, 5, 5])

In [60]:
m[:,1]

array([0, 0, 7, 1, 8])

In [61]:
m[:,4]

array([8, 0, 3, 4, 6])

In [62]:
m

array([[7, 0, 7, 6, 8],
       [3, 0, 3, 3, 0],
       [4, 7, 8, 5, 3],
       [5, 1, 3, 1, 4],
       [5, 8, 8, 2, 6]])

In [63]:
m[0,:]

array([7, 0, 7, 6, 8])

In [64]:
m[0]

array([7, 0, 7, 6, 8])

In [65]:
m[1,:]

array([3, 0, 3, 3, 0])

In [66]:
m[0:2,0:3]

array([[7, 0, 7],
       [3, 0, 3]])

In [67]:
m[:,0:2]

array([[7, 0],
       [3, 0],
       [4, 7],
       [5, 1],
       [5, 8]])

In [68]:
m[1:3,0:2]

array([[3, 0],
       [4, 7]])

# Acting on a Subset

In [71]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[1, 3, 5, 8, 8],
       [6, 9, 4, 8, 9],
       [3, 5, 7, 0, 5],
       [0, 7, 6, 7, 1],
       [5, 3, 0, 7, 7]])

In [72]:
sub_a = a[0:3,0:2]
sub_a

array([[1, 3],
       [6, 9],
       [3, 5]])

In [73]:
sub_a[0,0] = 99999
sub_a[1,1] = 888

In [74]:
sub_a

array([[99999,     3],
       [    6,   888],
       [    3,     5]])

In [75]:
a

array([[99999,     3,     5,     8,     8],
       [    6,   888,     4,     8,     9],
       [    3,     5,     7,     0,     5],
       [    0,     7,     6,     7,     1],
       [    5,     3,     0,     7,     7]])

In [80]:
m = np.random.randint(10, size = (5,5))
m

array([[3, 8, 5, 4, 4],
       [2, 9, 1, 2, 7],
       [9, 7, 8, 3, 3],
       [2, 8, 1, 8, 5],
       [4, 5, 8, 1, 8]])

In [81]:
sub_b = m[0:3,0:2].copy()
sub_b

array([[3, 8],
       [2, 9],
       [9, 7]])

In [82]:
sub_b[0,0] = 9999

In [83]:
sub_b

array([[9999,    8],
       [   2,    9],
       [   9,    7]])

In [84]:
m

array([[3, 8, 5, 4, 4],
       [2, 9, 1, 2, 7],
       [9, 7, 8, 3, 3],
       [2, 8, 1, 8, 5],
       [4, 5, 8, 1, 8]])

# Accessing Elements with Fancy Index

In [1]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
v[1]

3

In [3]:
v[3]

9

In [4]:
v[5]

15

In [5]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [6]:
a = [1,3,5]

In [7]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
v[a]

array([ 3,  9, 15])

In [9]:
# fancy in two sizes

In [10]:
m = np.arange(9).reshape((3,3))

In [11]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
line = np.array([0,1])
column = np.array([1,2])

In [13]:
m[line, column]

array([1, 5])

In [14]:
# simple index and fancy index

In [15]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
m[0, [1,2]]

array([1, 2])

In [19]:
# slice and fancy

In [18]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Conditional Element Operations

In [20]:
import numpy as np
v = np.array([1,2,3,4,5])

In [21]:
v < 3

array([ True,  True, False, False, False])

In [22]:
v[v < 3]

array([1, 2])

In [23]:
v[v > 3]

array([4, 5])

In [24]:
v[v >= 3]

array([3, 4, 5])

In [25]:
v[v <= 3]

array([1, 2, 3])

In [26]:
v[v == 3]

array([3])

In [27]:
v[v != 3]

array([1, 2, 4, 5])

In [28]:
v

array([1, 2, 3, 4, 5])

In [29]:
v * 2

array([ 2,  4,  6,  8, 10])

In [30]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [31]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [32]:
v ** 2

array([ 1,  4,  9, 16, 25])

# Mathematical Operations

In [34]:
import numpy as np
v = np.array([1,2,3,4,5])

In [35]:
v - 1

array([0, 1, 2, 3, 4])

In [36]:
v * 5

array([ 5, 10, 15, 20, 25])

In [37]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [38]:
v * 5 / 10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [39]:
# ufunc

In [40]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [41]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [42]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [43]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [44]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [45]:
v ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [46]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [47]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [48]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [49]:
np.absolute(np.array([-3]))

array([3])

In [50]:
np.sin(360)

0.9589157234143065

In [51]:
np.cos(180)

-0.5984600690578581

In [52]:
v = np.array([1,2,3])

In [53]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [54]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [55]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [56]:
?np

Type:        module
String form: <module 'numpy' from '/lib/python3.10/site-packages/numpy/__init__.py'>
File:        /lib/python3.10/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``

In [57]:
# cheatsheet

# Solving Equations with Two Unknowns with NumPy

In [58]:
import numpy as np

**5 * x0 + x1 = 12**

**x0 + 3 * x1 = 10**

In [61]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [62]:
a

array([[5, 1],
       [1, 3]])

In [63]:
b

array([12, 10])

In [64]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])